"""empty message

Revision ID: 4e047c6f5a92
Revises: 3eb176400dac
Create Date: 2020-03-27 13:53:13.224185

"""

# revision identifiers, used by Alembic.
revision = '4e047c6f5a92'
down_revision = '3eb176400dac'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE OR REPLACE FUNCTION ST_CreateFishnet(
           nrow integer, --1
           ncol integer, --2
           xsize numeric(19,9), --3
           ysize numeric(19,9), --4
           x0 numeric(19,9) DEFAULT 0, --5 
           y0 numeric(19,9) DEFAULT 0, --6
           OUT "row" integer, 
           OUT col integer,
           OUT geom geometry)
           RETURNS SETOF record AS
          $$
          SELECT i + 1 AS row, j + 1 AS col, 
          ST_Translate(
           cell
          , j * $3 + $5, i * $4 + $6
          )
          AS geom
          FROM generate_series(0, $1 - 1) AS i,
           generate_series(0, $2 - 1) AS j,
          (
          SELECT ST_PolygonFromText('POLYGON((0 0, 0 '||$4||', '||$3||' '||$4||', '||$3||' 0,0 0))', 4326) AS cell
          ) AS foo;
          $$ LANGUAGE sql IMMUTABLE STRICT;
    """)

    op.execute("GRANT ALL PRIVILEGES ON FUNCTION ST_CreateFishnet(nrow integer, ncol integer, xsize numeric, ysize numeric, x0 numeric, y0 numeric) TO postgres;")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP FUNCTION IF EXISTS ST_CreateFishnet(nrow integer, ncol integer, xsize numeric, ysize numeric, x0 numeric, y0 numeric)')
    ### end Alembic commands ###
